image: java:8

stages:
  - package
  - deploy

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

package:
  stage: package
  script:
    - ./gradlew assemble
  artifacts:
    expire_in: 1 hour
    paths:
      - build/libs/*.jar

deploy:
  stage: deploy
  dependencies:
    - package
  script:
    - ./gradlew artifactoryPublish
  only:
    - tags
